---
title: "Standings board"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
library(readr) ; library(dplyr) ; library(kableExtra) ; library(DT)
dedo = as.data.frame(read_csv("11_super_league_2013-14.csv"))
dedo$HomeTeam = as.factor(dedo$HomeTeam)
dedo$AwayTeam = as.factor(dedo$AwayTeam)

dedo.result = dedo[, 1:10]

dedo.odds = dedo[, 11:52]

dedo.standard.odds = dedo.odds[, -c(25:42)]

lista = NULL
for(i in 0:(ncol(dedo.standard.odds)/3-1)){
  k = c((3*i+1):(3*i+3))
  lista[[i+1]] = dedo.standard.odds[,k]
}

names(lista) = sub("H$", "", names(dedo.standard.odds)[grepl("H$", names(dedo.standard.odds))])
```


```{r, warning=FALSE, include = FALSE}
library(ggplot2)
library(magick)

dedo.test = dedo
standings = data.frame(Team = levels(dedo$HomeTeam), Points = rep(0, length(levels(dedo$HomeTeam))), kit = c("white", "yellow", "lightblue", "blue", "yellow", "brown", "pink", "lightgreen", "grey", "red", "green", "yellow", "brown", "chocolate", "black", "red", "blue", "darkgreen"))
standings

lista = list(rep(NULL, 9))
for(j in 1:(nrow(dedo)/9)){
  
  for (i in 1:9) {
    
    if(isTRUE((dedo.test$FTR[i] == "H"))){
      standings$Points[which(standings$Team %in% standings[standings$Team == dedo.test$HomeTeam[i],])] = standings$Points[which(standings$Team %in% standings[standings$Team == dedo.test$HomeTeam[i],])] + 3
    } 
    else if(isTRUE((dedo.test$FTR[i] == "D"))){
      standings$Points[which(standings$Team %in% standings[standings$Team == dedo.test$HomeTeam[i],])] = standings$Points[which(standings$Team %in% standings[standings$Team == dedo.test$HomeTeam[i],])] + 1
      standings$Points[which(standings$Team %in% standings[standings$Team == dedo.test$AwayTeam[i],])] = standings$Points[which(standings$Team %in% standings[standings$Team == dedo.test$AwayTeam[i],])] + 1
    } 
    else if(isTRUE((dedo.test$FTR[i] == "A"))){
      standings$Points[which(standings$Team %in% standings[standings$Team == dedo.test$AwayTeam[i],])] = standings$Points[which(standings$Team %in% standings[standings$Team == dedo.test$AwayTeam[i],])] + 3
    }
  }
  dedo.test = dedo.test[-c(1:9),]
  lista[[j]] = standings
}

lista.plot = NULL

for(i in 1:length(lista)){
  lista.plot[[i]] = ggplot(lista[[i]], aes(x = reorder(Team, Points), y = Points)) +
    geom_bar(stat = "identity", fill = standings$kit) +
    coord_flip() +
    ylim(0, 3*i) +
    labs(title = paste("Standing Board: Week", i), x = "Team", y = "Points")
}

for (i in seq_along(lista.plot)) {
  ggsave(paste0("plot_", i, ".png"), lista.plot[[i]])
}
```

```{r, echo = FALSE}
frames = image_read(c(paste0("plot_", 1:34, ".png")))
animation = image_animate(frames, fps = 0.5, loop = 0)
animation
```